---
conditions:
  all:
    - fact: payload.issue.user.login
      operator: equal
      value: jefeish

event:
  type: issuesCreateComment
  params:
    data: Let's play by the Rules... This is a Client Rule! ...from a 'special' place ;)

# default is '1'
priority: 1
